

scene_name: ???
data_dir: ???
open_eqa_questions: ${oc.env:OPEN_EAQ_UTILS_CFG_DIR}/open-eqa-v0.json
open_eqa:
  scene_name: ${scene_name}
  data_dir: ${data_dir}
  rgb_dir: ${open_eqa.data_dir}/${open_eqa.scene_name}/rgb
  depth_dir: ${open_eqa.data_dir}/${open_eqa.scene_name}/depth
  semantic_dir: ${open_eqa.data_dir}/${open_eqa.scene_name}/semantic
  poses_dir: ${open_eqa.data_dir}/${open_eqa.scene_name}/poses
  bins_voxels_2d_fn: ${open_eqa.data_dir}/${open_eqa.scene_name}/bins_voxel_map_2d.pkl
  bins_voxels_3d_fn: ${open_eqa.data_dir}/${open_eqa.scene_name}/bins_voxel_map_3d.pkl
  intrinsics: ${load:${open_eqa.data_dir}/${open_eqa.scene_name}/intrinsics.yaml}